spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/acl_demo?userSSL=false&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: true