version: '3.1'
services:
  mysql:
    image: mysql:8.0.20
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD=12345"
    ports:
      - "3306:3306"